<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519213258 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, severity VARCHAR(20) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, sent_whatsapp BOOLEAN NOT NULL, is_extreme_event BOOLEAN NOT NULL, economic_impact JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, farm_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17FD46C165FCFA0D ON alert (farm_id)');
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_count INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E9A76ED395 ON conversation (user_id)');
        $this->addSql('CREATE TABLE conversation_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, content TEXT NOT NULL, media_type VARCHAR(20) DEFAULT NULL, media_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2DEB3E759AC0396 ON conversation_message (conversation_id)');
        $this->addSql('CREATE TABLE crop_operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, type VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, duration_hours DOUBLE PRECISION DEFAULT NULL, operator VARCHAR(100) DEFAULT NULL, cost_eur DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parcel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8DCD476465E670C ON crop_operation (parcel_id)');
        $this->addSql('CREATE TABLE economic_params (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, oil_price_eur DOUBLE PRECISION NOT NULL, water_cost_eur DOUBLE PRECISION NOT NULL, labor_cost_eur DOUBLE PRECISION NOT NULL, default_yield_kg_ha DOUBLE PRECISION NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, farm_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C36A99765FCFA0D ON economic_params (farm_id)');
        $this->addSql('CREATE TABLE farm (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, surface DOUBLE PRECISION NOT NULL, soil_type VARCHAR(50) NOT NULL, municipality VARCHAR(100) NOT NULL, altitude INT NOT NULL, distance_sea_km DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5816D045A76ED395 ON farm (user_id)');
        $this->addSql('CREATE TABLE farm_season_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, season VARCHAR(20) NOT NULL, actual_yield_kg DOUBLE PRECISION DEFAULT NULL, actual_oil_liters DOUBLE PRECISION DEFAULT NULL, oil_quality VARCHAR(50) DEFAULT NULL, pest_events JSON DEFAULT NULL, disease_events JSON DEFAULT NULL, treatments_count INT NOT NULL, irrigation_total_mc DOUBLE PRECISION DEFAULT NULL, weather_summary JSON DEFAULT NULL, predicted_yield_kg DOUBLE PRECISION DEFAULT NULL, prediction_error_pct DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, farm_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FBDDE8A65FCFA0D ON farm_season_record (farm_id)');
        $this->addSql('CREATE TABLE organic_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, commercial_name VARCHAR(255) NOT NULL, active_substance VARCHAR(255) NOT NULL, registration_number VARCHAR(100) DEFAULT NULL, is_allowed_organic BOOLEAN NOT NULL, max_dose_per_ha DOUBLE PRECISION DEFAULT NULL, waiting_days INT DEFAULT NULL, cost_per_ha DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE parcel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, surface DOUBLE PRECISION NOT NULL, tree_count INT NOT NULL, variety VARCHAR(100) NOT NULL, planting_year INT NOT NULL, is_biological BOOLEAN NOT NULL, altitude INT DEFAULT NULL, slope DOUBLE PRECISION DEFAULT NULL, aspect VARCHAR(20) DEFAULT NULL, wind_exposure VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, farm_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C99B5D6065FCFA0D ON parcel (farm_id)');
        $this->addSql('CREATE TABLE prediction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, result JSON NOT NULL, confidence DOUBLE PRECISION NOT NULL, method VARCHAR(50) NOT NULL, explanation_text TEXT DEFAULT NULL, scenarios JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, target_date DATE NOT NULL, farm_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_36396FC865FCFA0D ON prediction (farm_id)');
        $this->addSql('CREATE TABLE prediction_accuracy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actual_value DOUBLE PRECISION NOT NULL, error_absolute DOUBLE PRECISION NOT NULL, error_pct DOUBLE PRECISION NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, validated_by VARCHAR(100) DEFAULT NULL, prediction_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58895195449DFD9E ON prediction_accuracy (prediction_id)');
        $this->addSql('CREATE TABLE sensor_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sensor_type VARCHAR(50) NOT NULL, value DOUBLE PRECISION NOT NULL, unit VARCHAR(20) NOT NULL, sensor_id VARCHAR(100) NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parcel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_801762CC465E670C ON sensor_data (parcel_id)');
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan VARCHAR(50) NOT NULL, stripe_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3C664D3A76ED395 ON subscription (user_id)');
        $this->addSql('CREATE TABLE treatment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, product_name VARCHAR(255) NOT NULL, active_substance VARCHAR(255) NOT NULL, dose_per_ha DOUBLE PRECISION NOT NULL, dose_unit VARCHAR(20) NOT NULL, total_quantity DOUBLE PRECISION DEFAULT NULL, target_pest VARCHAR(100) NOT NULL, application_method VARCHAR(100) DEFAULT NULL, weather_conditions VARCHAR(255) DEFAULT NULL, operator VARCHAR(100) DEFAULT NULL, is_organic BOOLEAN NOT NULL, registered_via VARCHAR(20) NOT NULL, cost_eur DOUBLE PRECISION DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parcel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98013C31465E670C ON treatment (parcel_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, phone VARCHAR(20) DEFAULT NULL, whatsapp_opt_in BOOLEAN NOT NULL, language VARCHAR(5) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE weather_cache (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, date DATE NOT NULL, data JSON NOT NULL, source VARCHAR(50) NOT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C165FCFA0D FOREIGN KEY (farm_id) REFERENCES farm (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_message ADD CONSTRAINT FK_2DEB3E759AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE crop_operation ADD CONSTRAINT FK_E8DCD476465E670C FOREIGN KEY (parcel_id) REFERENCES parcel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE economic_params ADD CONSTRAINT FK_1C36A99765FCFA0D FOREIGN KEY (farm_id) REFERENCES farm (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE farm ADD CONSTRAINT FK_5816D045A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE farm_season_record ADD CONSTRAINT FK_6FBDDE8A65FCFA0D FOREIGN KEY (farm_id) REFERENCES farm (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parcel ADD CONSTRAINT FK_C99B5D6065FCFA0D FOREIGN KEY (farm_id) REFERENCES farm (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prediction ADD CONSTRAINT FK_36396FC865FCFA0D FOREIGN KEY (farm_id) REFERENCES farm (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prediction_accuracy ADD CONSTRAINT FK_58895195449DFD9E FOREIGN KEY (prediction_id) REFERENCES prediction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sensor_data ADD CONSTRAINT FK_801762CC465E670C FOREIGN KEY (parcel_id) REFERENCES parcel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE treatment ADD CONSTRAINT FK_98013C31465E670C FOREIGN KEY (parcel_id) REFERENCES parcel (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C165FCFA0D');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E9A76ED395');
        $this->addSql('ALTER TABLE conversation_message DROP CONSTRAINT FK_2DEB3E759AC0396');
        $this->addSql('ALTER TABLE crop_operation DROP CONSTRAINT FK_E8DCD476465E670C');
        $this->addSql('ALTER TABLE economic_params DROP CONSTRAINT FK_1C36A99765FCFA0D');
        $this->addSql('ALTER TABLE farm DROP CONSTRAINT FK_5816D045A76ED395');
        $this->addSql('ALTER TABLE farm_season_record DROP CONSTRAINT FK_6FBDDE8A65FCFA0D');
        $this->addSql('ALTER TABLE parcel DROP CONSTRAINT FK_C99B5D6065FCFA0D');
        $this->addSql('ALTER TABLE prediction DROP CONSTRAINT FK_36396FC865FCFA0D');
        $this->addSql('ALTER TABLE prediction_accuracy DROP CONSTRAINT FK_58895195449DFD9E');
        $this->addSql('ALTER TABLE sensor_data DROP CONSTRAINT FK_801762CC465E670C');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3A76ED395');
        $this->addSql('ALTER TABLE treatment DROP CONSTRAINT FK_98013C31465E670C');
        $this->addSql('DROP TABLE alert');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE conversation_message');
        $this->addSql('DROP TABLE crop_operation');
        $this->addSql('DROP TABLE economic_params');
        $this->addSql('DROP TABLE farm');
        $this->addSql('DROP TABLE farm_season_record');
        $this->addSql('DROP TABLE organic_product');
        $this->addSql('DROP TABLE parcel');
        $this->addSql('DROP TABLE prediction');
        $this->addSql('DROP TABLE prediction_accuracy');
        $this->addSql('DROP TABLE sensor_data');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE weather_cache');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
